### ISSUE TITLE
Error due to rendering an inconsistent number of hooks

### ISSUE THREAD

**Issue by agex-n7** [docusealco/docuseal-react#2]
## Description
When triggering a rerender of the component that renders the `DocusealForm`, it throws an error due to rendering a different amount of hooks.

## Steps to reproduce / example:
Can easily be reproduced:
https://codesandbox.io/s/nostalgic-kilby-tzqfpd?file=/src/App.tsx

## Fix
The following condition should be removed from the condition to render hooks on the client side:
```ts
// src/form.tsx:40
!document.getElementById(scriptId))
```

**Comment by AlexBTurchyn** [comment]
@agex-n7 We fixed this bug in the last release (1.0.13). Thanks for the help.

**Comment by agex-n7** [comment]
Great, thanks for the fix.
