### ISSUE TITLE
withDecline does not work

### ISSUE THREAD

**Issue by rosskhanas** [docusealco/docuseal-react#6]
I follow the docs: https://www.docuseal.co/docs/embedded/form#react

My code:
```
<DocusealForm
        customCss="#expand_form_button, #submit_form_button { background-color: #7BEEB3; border: none; color: #000000; } #submit_form_button:hover { background-color: #7BEEB333; }"
        email={customer.email}
        minimize
        src={submitter.embedSrc}
        withDecline
        withTitle={false}
        onComplete={async () => {}}
        onDecline={() => {}}
      />
```

Result - no "Decline" button:
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/a7b13eaf-f053-42a8-ba7d-6337e7ca38af">

**Comment by omohokcoj** [comment]
Hi @rosskhanas can you please try withDecline={true} - make sure it's the latest react npm version
Let me know if it works

**Comment by rosskhanas** [comment]
@omohokcoj just tried `1.0.47` and explicitly pass `true`, it does not work. Here is a piece of HTML:

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/5ad6f2ba-9658-43cd-a126-6714ae7ba39d">

**Comment by omohokcoj** [comment]
@rosskhanas are you using react client side render - or maybe some SSR engine?
I wonder what happens if you pass withDecline={'true'} ?

**Comment by rosskhanas** [comment]
@omohokcoj with the string "true" it works:
<img width="882" alt="image" src="https://github.com/user-attachments/assets/338fa3e1-0bb3-4321-ba0d-6c74f3bc7454">


We use next with server rendering, but this part of the page is a client-only component and is not rendered on a server.

**Comment by omohokcoj** [comment]
@rosskhanas it must be related to how your next app renders html attributes with react - by default true and false boolean is rendered explicitly as strings (data-with-decline="true"). But it seems like in your app it's not rendered explicitly - might be related to the nextjs version/configs.
Using 'true'/'false' prop strings should solve the issue in your nextjs app

**Comment by rosskhanas** [comment]
@omohokcoj I will pass true as string then, thank you for help!
